src/components/LoginLayout/LoginLayout.scss, src/components/Saved/Saved.js, src/components/Saved/index.js, src/components/Settings/Settings.js, src/components/Settings/Settings.scss
Added user feedback when changing settings
=> Added user feedback when saving settings

src/actions/balancesActions.js, src/actions/dapps/makeBalancesAction.js, src/actions/dapps/makeTestInvokeActions.js, src/components/Browser/RequestsProcessor/GetBalance/GetBalance.js, src/components/Browser/RequestsProcessor/GetBalance/index.js, src/components/Browser/RequestsProcessor/RequestProcessor.js, src/components/Browser/RequestsProcessor/mappings.js, src/util/getBalances.js
Extended the balances API with an optional parameter to query other people their balance
Solves issue #82
=> feat(balances): extended the balances API 

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md, LICENSE, README.md, package.json
Added issue, PR templates and added contributions file + updated Readme
=> issue + PR templates

public/welcome.html
Closing #110 and using this instead.
This prevents users from seeing these pages from within the client. They should pop out to the user's default system browser.
I've simply added blank targets on non-client links to avoid viewing the pages in the nOS client that shouldn't be viewed there.
N/A
Tested Locally.
Fixes #
=> Blank target to nOS client and neoblog dApp Links

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
This updates some contributor documentation to add clarity around chores that previously didn't fall into any category.
There was no documented way to categorize small chores like code cleanup.
N/A
N/A
N/A
=> Update contributing guide and PR template

src/components/Register/AccountDetails/SaveAccount/SaveAccount.js
This is just a small bit of cleanup from merging the registration feature related to saving an account to an existing wallet.
Some of our messaging, syntax, and logic was inconsistent.
Verified the success & error alert messages matches in the client.
N/A
N/A
=> Cleaned up register messaging and logic

docs/create-your-own-dapp.md
Added prerequisites steps for creating dapps. Minor changes in gettingStarted markdown file.
Getting started document didn't mention about the nOS browser building part. Added a few lines of explanation for that.
Just trying to add more clarity to the docs, as I couldn't figure out how can nOS browser be used to run the apps.
Fixes #
=> Prerequisites added in the docs

config-overrides.js
Unable to resolve any module on windows machines
It now does work :)
yarn build on a windows machine where it did not work previously
None
=> chore(src): windows import resolver build fix

.eslintignore, .eslintrc.json, __tests__/browser/components/RequestsProcessor/GetAddress/GetAddress.test.js, __tests__/browser/components/RequestsProcessor/GetAddress/index.test.js, __tests__/browser/components/RequestsProcessor/GetBalance/GetBalance.test.js, __tests__/browser/components/RequestsProcessor/GetBalance/index.test.js, __tests__/testHelpers.js, package.json, src/browser/actions/makeBalancesActions.js, src/browser/components/RequestsProcessor/GetBalance/GetBalance.js, src/browser/components/RequestsProcessor/mappings.js, yarn.lock
This adds a thorough set of unit tests around the `GetBalance` and `GetAddress` components & containers.
We need to have trust that what we're building works as expected, and also that we don't break it as we continue working on it.
I ran the test suite!
Contributes towards #137, but doesn't close it yet.
=> chore(tests): added tests for GetBalance & GetAddress requests

public/electron.js
Adds `X-nOS-Version` header to all requests.  The value is the version defined in `package.json`.
This will allow webapps to check if the request is coming from the nOS client and load accordingly.
Navigated to http://www.whatsmyua.info
N/A
=> feat(browser): add X-nOS-Version request header

__tests__/root/components/App/Routes.test.js, public/welcome.html, src/browser/reducers/browserReducer.js
This changes the start page to lead to the nOS Contributions dashboard.  It also adds a link from the welcome screen leading to the app.
We want users/teams to be able to report & track their contributions towards nOS.
I opened the app, and it took me there.  I also opened a new tab, and it took me there.
N/A
=> feat(browser): My nOS

package.json
Updates package version to 0.2.0.
We'd like to get a release together. 😄
It hasn't been.
N/A
=> chore(package): update version to 0.2.0

public/resolve.js
Domain service resolver smart contract updated.
=> (chore)Update domain service script hash

package.json
Updates app version to 0.2.1.
We'd like to get a release out to fix the copy/paste issue on inputs.
Via all other PRs.
N/A
N/A
=> chore(package): update version to 0.2.1

README.md
Adding a badge to show the latest release.
Best way for Github users to see if they're on the latest version.
Looked very closely at the badge and determined it showed the latest version
No screenshot needed, go to README.md ;)
none
=> chore(docs): add release badge

.circleci/config.yml, .eslintrc.json, package.json, src/main/index.js, src/renderer/browser/actions/makeStorageActions.js, src/renderer/browser/components/ButtonBar/ButtonBar.js, src/renderer/browser/components/RequestsProcessor/RequestProcessor.js, src/renderer/browser/components/Tab/Tab.js, src/renderer/login/util/ledger.js, src/renderer/root/store/configureStore.js, src/renderer/shared/components/Forms/Button/Button.js, src/renderer/shared/hocs/withProgressChange.js, yarn.lock
This cherry-picks the eslint-related greenkeeper PR's into a single PR where the overall changes can be seen in unison.
Greenkeeper had various eslint-related package updates, but it was hard to see the effect of each individual within our client codebase.  This helps to understand the impact of the change so that we can override rules and update syntax as necessary.
`yarn lint`
N/A
=> Updated eslint and associated packages

src/renderer/settings/components/NetworkPanel/NetworkPanel.scss, src/renderer/shared/components/Icon/Icon.js
Added correct prefix for 'check-circle' icon, so it won't cause an error and will render on page, and changed styles in NetworkPanel for better view on small screens.
Missing prefix caused errors and this icon didn't show up on page
Manual testing by changing selected network
Fixes #281
=> chore(Icon component):Correct prefix for check-circle icon and some styling

.circleci/config.yml, README.md, package.json, yarn.lock
Adds the codecov report to the CI build & coverage badge to the readme.
We want to know what our test coverage looks like as we work on code to ensure that we are moving forward in terms of coverage.
Saw the report and the badge.
<a href="https://codecov.io/gh/nos/client">
</a>
N/A
=> chore(codecov): added codecov coverage report

src/renderer/root/util/updateNetworks.js, src/renderer/settings/values/networks.js
nOSNet is the public nOS Testnet. Added to the available networks in Settings.
Fixes #
=> Add nOSNet Custom Network

package.json
Updates nOS client version to 0.2.2
We'd like to get a release out to include the nOSNet network & name-service smart contract changes.
N/A
N/A
N/A
=> chore(package): updated version to 0.2.2

src/renderer/settings/actions/currentNetworkActions.js, src/renderer/settings/components/NetworkPanel/NetworkPanel.js, src/renderer/settings/values/networks.js, src/renderer/shared/hocs/withLoadingProp.js
removed hardcoded fallbacks 
set fallback to nOSNet
Many reasons
Cleared out networks after adding one (one way triggering the fallback)
Fixes #
=> chore(settings): set nOSNet as default fallback

package.json, src/renderer/settings/actions/currentNetworkActions.js, src/renderer/settings/components/NetworkPanel/NetworkPanel.js, src/renderer/settings/values/networks.js, src/renderer/shared/hocs/withLoadingProp.js, yarn.lock
**DO NOT SQUASH MERGE**
This includes an additional fix that is needed for the 0.2.2 release.
We want to provide a client version for users to access nOSNet by default.
Constantly.
Many.
=> [Release] Version 0.2.2 (redo)

src/renderer/browser/reducers/browserReducer.js
An extra argument was included, but is not actually needed any longer.
This broke navigating.
Loading a page.
N/A
=> chore(nav): fixed navigation check to remove unneeded argument

src/common/stylesheets/variables.scss, src/renderer/account/components/Account/Account.js, src/renderer/account/components/Account/Account.scss, src/renderer/account/components/AccountPanel/AccountPanel.scss, src/renderer/account/components/AccountPanel/Holdings/Holdings.scss, src/renderer/account/components/SendPanel/SendPanel.scss, src/renderer/shared/components/Page/Page.js, src/renderer/shared/components/Page/Page.scss, src/renderer/shared/components/Page/index.js, src/renderer/shared/index.js
Adds responsive sizing to wallet screen, and restricts size for large displays.
We want the screens to look nice on all displays, not just one optimal resolution.
Resizing the browser and observing the results.
N/A
=> chore(wallet): responsive wallet

static/welcome.html
Current link leads to 404 error page
Fixes #
=> nOS docs link fix

src/renderer/shared/util/getBalances.js
This replaces the call to neoscan for NEO/GAS balances with a direct RPC call.  The less reliance we have on an endpoint that could go down, the better.
There's still a dependency on neoscan to determine the best RPC endpoint, but that is true for all our RPC calls presently.  The next step will be to come up with a way to no longer rely on that.
Don't want any single points of failure.
Fetching balances across networks.
N/A
=> chore(balance): use rpc to get account state

src/renderer/register/components/RegisterForm/RegisterForm.js, src/renderer/shared/components/Icon/Icon.js, src/renderer/shared/components/Tabs/Tabs.js
This fixes the registration form:
* submit was broken
* loading state wasn't being applied
* copy icon for account details wasn't displaying
Need registration to work, it's a core feature!
Smoke testing.
Fixes #421
=> chore(register): fixed registration form

__tests__/renderer/register/components/AccountDetails/AccountDetails.test.js, src/renderer/account/components/TransactionsPanel/Receive/Receive.js, src/renderer/account/components/TransactionsPanel/Receive/index.js, src/renderer/register/components/AccountDetails/AccountDatum/AccountDatum.js, src/renderer/register/components/AccountDetails/AccountDatum/index.js, src/renderer/root/components/App/Toasts/Toast/Toast.scss
Displays informational toast messages when the user copies info to the clipboard.
We have new toasts, so we should use them in appropriate spots.  We also should be consistent about how copying works in different places.
Smoke testing.
N/A
=> chore(toast): copy to clipboard info toasts

src/renderer/settings/components/GeneralSettings/GeneralSettings.js, src/renderer/shared/components/Forms/Label/Label.js
Previous PR, moving the labeled components in their own components broke 1 select, this PR resolves that
Client showed an error when navigating to settings page
going to settings page, no error
Fixes #
=> chore(settings): fixed settings select not showing label

package.json
Needs to be ignored
read desc
Fixes #
=> chore(deps): ignored electron-webpack

__tests__/renderer/account/components/TransactionsPanel/index.test.js, __tests__/renderer/account/index.test.js, __tests__/renderer/register/components/AccountDetails/AccountDatum/AccountDatum.test.js, __tests__/renderer/register/components/AccountDetails/AccountDetails.test.js, __tests__/renderer/shared/components/Forms/LabeledInput/index.test.js, __tests__/renderer/shared/components/Forms/LabeledSelect/index.test.js, package.json, src/renderer/shared/components/Forms/Label/Label.js, yarn.lock
=> Greenkeeper/monorepo.enzyme 3.5.0

src/renderer/login/components/LoginFormWalletFile/LoginFormWalletFile.js, src/renderer/login/components/LoginFormWalletFile/index.js, src/renderer/root/components/App/Toasts/Toast/Toast.js, src/renderer/settings/components/NetworkSettings/NetworkSettings.js, src/renderer/settings/components/NetworkSettings/index.js
Network settings didn't clear props and still showed a modal + toast
Also added some extra validation as you were able to add empty entries, resulting in errors
Replaced login error modal (with faulty import of wallet file) with an error toast
#489 Although this PR doesn't cover all issues with the toasts
manual testing, shall I write tests? 
Fixes #
=> chore(toasts): replaced modals with toasts, fixed network settings

package.json, yarn.lock
updated webpack and redux 
good practise, don't want the deps to become depricated
testing the app
Fixes #
=> Chore(deps): updated webpack/redux - removed redux from greenkeeper ignore

package.json
Updates version to 0.3.0.
To release version 0.3.0.
Constantly via PR's.
N/A
=> chore(package): updated version to 0.3.0

.circleci/config.yml, package.json, src/main/util/bindMenus.js
Bring master and develop into parity.  **DO NOT SQUASH MERGE.**
=> [Release] Version 0.3.0 (redo)

package.json
Updates version from 0.3.0 to 0.4.0.
To get a new client release out.
In every PR that we submit.
N/A
N/A
=> chore(package:) updated version to 0.4.0

src/common/values/networks.js
Change default network to MainNet.
This is for our TGE release, and we want the least amount of friction possible.
N/A
N/A
N/A
=> chore(network): default to MainNet

package.json
Bring master and develop into parity. **DO NOT SQUASH MERGE.**
=> [Release] Version 0.4.0 (redo)

src/renderer/settings/components/GeneralSettings/GeneralSettings.js, yarn.lock
Fixed an issue where you were not able to select currencies
it didn't work
clicking it and see the selected currency in the wallet section
/
Fixes #610
=> chore(generalSettings): fixed not being able to select currency

src/main/index.js, src/main/util/bindApplicationMenu.js, src/renderer/browser/components/DAppContainer/DAppContainer.js, static/preloadRenderer.js, static/preloads/handleZoom.js
Implements zoom in, out, and actual size.
Browser parity.
Using the menu options and keyboard shortcuts.
Fixes #596.
=> feat(menu): browser zoom

src/renderer/account/components/TransactionsPanel/Send/PriorityFee/PriorityFee.js, src/renderer/browser/components/RequestsProcessor/Invoke/index.js, src/renderer/browser/components/RequestsProcessor/Send/index.js, src/renderer/browser/hocs/withInvocationPrompt/index.js, src/renderer/browser/hocs/withPrompt/index.js, src/renderer/shared/components/Confirm/Confirm.js, src/renderer/shared/components/Confirm/Confirm.scss, src/renderer/shared/components/Modal/Modal.js
This adds the priority fee amount to the send & invoke modals.
The user should know if there is a fee associated with what they're about to do.
Smoke testing sending & invoking via an app made with create-react-app.
```jsx
const invoke = {
scriptHash,
operation,
args: [],
assets: { [NEO]: "0", [GAS]: "0.00001" }
};
const send = {
receiver: "AHF4FysVWcmzS5hT5rgR7MzuP79zYsXV8g",
asset: NEO,
amount: 1
};
return (
<React.Fragment>
<button className={classes.button} onClick={() => this.handleAlert(nos.send(send))}>
Send
</button>
<button className={classes.button} onClick={() => this.handleAlert(nos.invoke(invoke))}>
Good Invoke
</button>
</React.Fragment>
);
```
Partial fix for #611.
=> feat(tx): priority fee notice

package.json
Updates the package version to 0.4.1.
Preparing a release for ICO.
Via all prior PR's.
N/A
=> chore(package): update version to 0.4.1

package.json, yarn.lock
=> [Release] 0.4.1 Redo

src/renderer/account/components/AccountPanel/ClaimButton/index.js, src/renderer/browser/components/RequestsProcessor/ClaimGas/index.js, src/renderer/browser/hocs/withSignTransactionToast.js, src/renderer/shared/hocs/withProgressChange.js, src/renderer/shared/util/claimGas.js
Fixes "Claim GAS" button for ledger users.
Ledger users want to claim GAS too.
Claiming GAS on Ledger Nano S.
N/A
=> chore(claim): fixed gas claim for ledger

src/renderer/account/components/TransactionsPanel/Send/index.js, src/renderer/shared/hocs/withProgressChange.js, src/renderer/shared/util/sendAsset.js
Fixes "Send" feature for Ledger users.
Ledger users want to send assets & tokens too.
Sending GAS on Ledger Nano S.
N/A
=> chore(claim): fixed send assets/tokens for ledger

src/renderer/shared/components/Forms/Button/Button.scss, src/renderer/shared/components/Forms/PrimaryButton/PrimaryButton.scss
Updates button styles to match latest designs.
See designs.
Hovering mouse, clicking button, tabbing to button, etc.
N/A
=> chore(button): update styles

package.json
Updates package version to 0.4.2.
To release a new version.
N/A
N/A
N/A
=> Updated version to 0.4.2

package.json
Fixed version in package.json before release.
=> [Release] 0.4.2

src/common/util/getRPCEndpoint.js
This allows us to filter out bad nodes dynamically so that a release isn't required in the future when issues arise.
NEO nodes acting unreliable has bitten us too much during the ICO.
Using the app.
N/A
N/A
=> feat(rpc): filter nodes dynamically

src/common/util/getRPCEndpoint.js
Allow filtering NEO nodes dynamically.
=> [Release] 0.4.4

src/common/util/getRPCEndpoint.js
This fixes an issue with the current height detection.  We were selecting from all nodes instead of just "good" nodes.
Ensures the app works instead of getting failures.
Running the app and having a bad node have the greatest block height.
N/A
N/A
=> chore(rpc): select best height from good nodes

src/renderer/browser/actions/makeTestInvokeActions.js, src/renderer/browser/components/RequestsProcessor/TestInvoke/index.js, src/renderer/browser/util/createArrayScript.js, src/renderer/browser/util/validateScriptArgs.js
Allows you to use a raw script or array of {scriptHash, operation, args} for testinvokes
Chaining testinvokes (balanceOf calls, multiple non-intensive computations, ...)
Tested with a raw script and an object array of params and it all works!
Fixes #
=> feat(browser): multi testinvoke

package.json
=> chore(package): update version to 0.4.5

package.json, src/common/util/getRPCEndpoint.js, src/renderer/account/components/Account/index.js, src/renderer/account/components/AccountPanel/AccountPanel.scss, src/renderer/account/components/AccountPanel/Holdings/index.js, src/renderer/account/components/AccountPanel/TokenBalance/TokenBalance.js, src/renderer/account/util/formatBalance.js, src/renderer/browser/actions/makeTestInvokeActions.js, src/renderer/browser/components/RequestsProcessor/TestInvoke/index.js, src/renderer/browser/util/createArrayScript.js, src/renderer/browser/util/validateScriptArgs.js, src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.js, src/renderer/shared/util/getBalances.js, src/renderer/shared/util/getTokens.js, src/renderer/shared/values/assets.js
=> [Release] 0.4.5

package.json
=> chore(package): update version to 0.4.6

__tests__/renderer/browser/components/RequestsProcessor/Send/index.test.js, package.json, src/common/util/getRPCEndpoint.js, src/renderer/browser/actions/makeInvokeActions.js, src/renderer/browser/actions/makeSendActions.js, src/renderer/shared/util/claimGas.js, src/renderer/shared/util/sendAsset.js
Includes custom nOS RPC nodes & correct RPC endpoint usage for sends & invokes
=> [Release] 0.4.6

src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.scss
=> [Release] 0.4.6 redo

.circleci/config.yml, README.md, package.json, renovate.json
Replaced greenkeeper with renovate
- It now combines PRs of eslint, fortawesome and babel in 1 PR to avoid noice
- Set ranges for electron/webpack to avoid complete ignorance of deps
- It now creates just 1 branch per dep instead of 1 branch per update (we now have 50+ branches because of greenkeeper --> clutter, can't find chores/feats easily)
- It is now scheduled on each monday to avoid daily spam
not yet?? must be merged in I guess
Fixes #
=> feat(root): replaced greenkeeper with renovate

src/renderer/browser/components/RequestsProcessor/Send/index.js
Fixes ability to send assets with a ledger through the API 
Sending assets is/was broken through the API
Sending assets through the API manually
Fixes #781
=> chore(requestProcessor): fixed ledger tx for sending assets

src/renderer/browser/actions/makeClaimActions.js, src/renderer/browser/components/RequestsProcessor/ClaimGas/index.js, src/renderer/browser/components/RequestsProcessor/Send/index.js
Fixes the claimGas API 
Fixes claimGas not working for Ledger
Testing the API I noticed that the `withPrompt` didn't work anymore and thus rendered the claimGas API function useless as this threw an error. This was due to the withPrompt expecting a function instead of a string.
Manually
Fixes #
=> chore(requestProcessor): fixed claimGas API prompt + fix for ledger

src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.scss, src/renderer/root/components/AuthenticatedLayout/Tab/Tab.scss
fixed button overlay and remove text selection of tabs
the extra tab button overlayed the windows buttons min/max/close buttons and the tab title text was selectable
manually
Fixes #
=> chore(tabs): fixed button overlay and remove text selection

src/renderer/browser/components/RequestsProcessor/Decrypt/index.js, src/renderer/browser/components/RequestsProcessor/Encrypt/index.js, src/renderer/browser/components/RequestsProcessor/GetPublicKey/index.js
Switched the withCalls, with WithInitialCalls to prevent accidental duplicate calls
read above
manual
Fixes #
=> chore(requestProcessor): fixed enc/decr/getPub calls

.circleci/config.yml
removed auto build on each PR
It is only needed for master branches
Fixes #
=> chore(circleci): update config

src/renderer/account/components/TransactionsPanel/Send/ConversionInput/ConversionInput.js
removes the hiding of the disclaimer
no need to hide
Fixes #
=> chore(send): remove auto hide of disclaimer

package.json
bump version to 0.5.0
we need a release out
Fixes #
=> chore(package): bump version

src/main/index.js, src/renderer/account/components/AccountPanel/Breakdown/BreakdownChart/BreakdownChart.js, src/renderer/account/components/AccountPanel/Breakdown/SectionLabel/SectionLabel.js, static/splash.html
update chart layout
fix splashscreen black edges
Fixes #
=> chore(chart): update threshold

package.json
fix the icon not displaying on linux
Fixes #261
=> chore(package): fix linux icon display

package.json
set default artifacts name
Fixes #
=> chore(package): set default artifact name

src/renderer/root/components/AuthenticatedLayout/Tabs/Tabs.js
exit app when closing last tab
#529 
Fixes #529
=> feat(tabs): exit app when closing last tab

src/main/index.js
set minimum window size
you could have it 20x20px
Fixes #737
=> chore(main): set minimum window size

package.json
=> chore(version): bump

src/renderer/account/components/AccountPanel/Breakdown/BreakdownChart/BreakdownChart.js, src/renderer/account/components/AccountPanel/Breakdown/BreakdownChart/index.js
fix faulty threshold calculation of the donut chart
it was faulty
Fixes #
=> chore(account): fix threshold calculation in donut chart

src/renderer/account/components/AccountPanel/Breakdown/BreakdownChart/BreakdownChart.js, src/renderer/account/components/AccountPanel/Breakdown/BreakdownChart/index.js
=> [RELEASE] 0.5.1 redo v2

README.md
updated readme
info for outside contributors 
Fixes #
=> chore(readme): update readme for new release process

.gitignore, dev-app-update.yml, src/main/index.js
disable update check in dev mode
client failed to build without the dev file or without the if statement
Fixes #
=> chore(autoUpdate): disable update check in dev mode

src/renderer/account/components/AccountPanel/Breakdown/BreakdownLoading/BreakdownLoading.scss, src/renderer/shared/images/account/accountLoading.svg
=> chore(account): smoothen loading

src/renderer/login/components/LoginButton/index.js, src/renderer/register/components/Register/Register.js, src/renderer/register/components/RegisterForm/RegisterForm.js
rename labels to be more convenient
rename labels to be more convenient
https://github.com/nos/client/issues/900
=> chore(account): rename labels

.circleci/config.yml, .eslintrc.json
update regex to accept `vX.X.X` tags for deployment
Fixes #
=> chore(circleci): update deployment requirements

package.json
=> [RELEASE] 0.5.2 (redo)

src/renderer/settings/actions/feeActions.js
change it as not everyone owns gas from the beginning
Fixes #
=> chore(tx): change default tx fee

src/renderer/login/components/LoginFormProfile/LoginFormProfile.js
=> chore(login): fix prop validation error

src/renderer/account/components/TransactionsPanel/Send/Send.js, src/renderer/account/components/TransactionsPanel/Send/index.js, src/renderer/account/components/TransactionsPanel/TransactionsLoading/TransactionsLoading.js, src/renderer/shared/util/getBalances.js, src/renderer/shared/values/assets.js
=> [RELEASE] 0.5.2 redo

.circleci/config.yml
=> chore(circleci): linux deployment fix

.editorconfig, __tests__/renderer/appstore/components/AppButton/AppButton.test.js, __tests__/renderer/appstore/components/AppButton/__snapshots__/AppButton.test.js.snap, __tests__/renderer/appstore/components/AppStore/AppStore.test.js, __tests__/renderer/appstore/components/AppStore/__snapshots__/AppStore.test.js.snap, __tests__/renderer/appstore/components/CategoryTitle/CategoryTitle.test.js, __tests__/renderer/appstore/components/CategoryTitle/__snapshots__/CategoryTitle.test.js.snap, __tests__/testHelpers.js, package.json, src/common/stylesheets/variables.scss, src/renderer/appstore/actions/getAppStoreData.js, src/renderer/appstore/components/AppButton/AppButton.js, src/renderer/appstore/components/AppButton/AppButton.scss, src/renderer/appstore/components/AppButton/index.js, src/renderer/appstore/components/AppStore/AppStore.js, src/renderer/appstore/components/AppStore/AppStore.scss, src/renderer/appstore/components/AppStore/index.js, src/renderer/appstore/components/CategoryTitle/CategoryTitle.js, src/renderer/appstore/components/CategoryTitle/CategoryTitle.scss, src/renderer/appstore/components/CategoryTitle/index.js, src/renderer/appstore/components/index.js, src/renderer/appstore/index.js, src/renderer/appstore/shape/appShape.js, src/renderer/browser/reducers/browserReducer.js, src/renderer/browser/values/browserValues.js, src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.js, src/renderer/root/components/Root/Root.js, src/renderer/shared/images/appstore/bg-shape-1.svg, src/renderer/shared/util/getInternalPageComponent.js
App store view
This adds a new native window that displays a list of apps and tools available on nOS
Testing and displaying API responses
Fixes #
=> feat(app): app store

src/renderer/appstore/components/AppButton/AppButton.scss, src/renderer/appstore/components/AppStore/AppStore.scss
Scrolling on the background didn't work, this fixes it
Fix was needed
Tested it by trying out scrolling
Fixes #
=> chore(appstore): fix scrolling on appstore background

__tests__/renderer/appstore/components/AppButton/__snapshots__/AppButton.test.js.snap, __tests__/renderer/appstore/components/AppStore/__snapshots__/AppStore.test.js.snap, __tests__/renderer/appstore/components/CategoryTitle/__snapshots__/CategoryTitle.test.js.snap
Tests were failing after updating enzym
^
Fixes #
=> chore(tests): fix enzym snapshot tests failing

src/main/index.js
Potentional fix for `Your browser does not support WebGL`
Hash Puppies didn't work for several people with low end GPUs
Fixes #
=> chore(main): ignore gpu blacklist for hw acceleration

.circleci/config.yml, package.json, src/main/index.js
=> sync master with develop

src/renderer/shared/values/themes.js
Uses dark theme by default.
Dark themes are becoming way more prevalent nowadays and are less of an assault for people's eyes. The new branding definitely fits well with the dark theme, too.
/
Fixes #
=> chore(theming): set dark theme as default

src/renderer/shared/wallet/Wallet.js, src/renderer/shared/wallet/WalletHelpers.js
Wallet should be async, since bip39.mnemonic returns a promise.
Leaving this unfixed breaks the sign in process
/
/
Fixes #
=> chore(wallet): bip39.mnemonic is async

src/renderer/account/components/Management/Account/Account.js, src/renderer/account/components/Management/Account/Account.scss, src/renderer/account/components/Management/EncryptedInput/EncryptedInput.js
* Keychain seed didn't have fluid width.
* It kept saying "Show & Unlock" even after unlocking
UI fixes
It works! 😄 
Fixes #
=> chore(account): key mgmt view ui fixes

src/renderer/account/components/Management/EncryptedInput/EncryptedInput.js, src/renderer/account/components/Management/Wallet/Wallet.js, src/renderer/account/components/Management/Wallet/Wallet.scss, src/renderer/account/components/Management/Wallets/Wallets.js
also cleaned up some props
fixes an issue with the encrypted input, which went bork due to bip39 updates
it was broken
Fixes #
=> chore(wallet): fix encrypted input not working and add color fallback

src/renderer/account/components/Portfolio/AccountPanel/Breakdown/Breakdown.js, src/renderer/account/components/Portfolio/AccountPanel/Breakdown/Breakdown.scss, src/renderer/account/components/Portfolio/TransactionsPanel/Send/ConversionInput/ConversionInput.js, src/renderer/account/components/Portfolio/TransactionsPanel/Send/ConversionInput/index.js, src/renderer/browser/components/RequestsProcessor/mappings.js, src/renderer/login/components/LoginForm/index.js, src/renderer/register/components/CreateAccount/RegisterForm/RegisterForm.js, src/renderer/register/components/VerifyAccount/index.js, src/renderer/shared/components/TokenIcon/TokenIcon.js, src/renderer/shared/images/tokens/nos.svg, static/preloadRenderer.js, static/preloads/api.js
- fix exposing of the API
- removed api V2
- Added nOS scripthash to API
- Added nOS icon to empty wallet state and overall in the app
- Fixes react state shift issue while registering and signing in
- Added dynamic text for register button depending on ledger selected or not
- Added coingecko url to send panel
- Show nOS Logo as empty wallet state
Fixes #
=> chore(app): prepare release

src/renderer/account/components/Management/Wallet/index.js, src/renderer/shared/actions/accountActions.js
Clear claimable balances when signing out or changing primary wallets.
The old claimable balance was still displayed upon changing accounts/wallets
Fixes #
=> chore(app): clear claimables balance when signing out or changing wallet

src/renderer/root/components/App/ButtonBar/ButtonBar.scss
Adjusts the colors of the min-max button hover and click states
Colors were not really well visible
Fixes #
=> chore(buttonBar): adjusted hover state colors of buttonbar

src/renderer/browser/components/RequestsProcessor/RequestsProcessor.js, src/renderer/browser/components/RequestsProcessor/index.js
fixes an issue which causes the browser to crash when unauthenticated and the application tries to use the nOS API
app crashed
Fixes #
=> chore(browser): prevents crash when accessing the nOS API while unauthenticated

src/renderer/browser/components/RequestsProcessor/RequestProcessor.js, src/renderer/browser/components/RequestsProcessor/RequestsProcessor.js, src/renderer/browser/components/RequestsProcessor/Unauthenticated/Unauthenticated.js, src/renderer/browser/components/RequestsProcessor/Unauthenticated/index.js
The fix, preventing the app from crashing while unauthenticated introduced another issue, which made the client crash when you tried to sign in while being on an unauthenticated page.
This PR resolves this issue.
Client crashed
Fixes #
=> chore(api): added unauthenticated component to nOS API

package.json
=> chore(package.json): bump version to 0.6

.circleci/config.yml
=> chore(circleci): update node version to new LTS

.circleci/config.yml
=> [RELEASE-1] 0.6.0

package.json
=> chore(package.json): adjust engines

package.json
=> chore(package.json): adjust node engines

.circleci/config.yml
=> chore(circleci): replace container image with custom image

.circleci/config.yml
=> chore(circleci): fix test coverage issue

renovate.json
commit type was set but wasn't used as semantic commits were not enabled
Fixes #
=> chore(renovate): enable semantic commits

.circleci/config.yml, renovate.json
=> chore(circleci): fix incorrect cache issue of circleci builds

config/webpack.renderer.js, package.json, yarn.lock
=> chore(config): fix css-loader breaking changes

__tests__/renderer/appstore/components/AppButton/__snapshots__/AppButton.test.js.snap, __tests__/renderer/appstore/components/AppStore/__snapshots__/AppStore.test.js.snap, __tests__/renderer/appstore/components/CategoryTitle/__snapshots__/CategoryTitle.test.js.snap, package.json, yarn.lock
=> chore(tests): fix snapshots

src/renderer/shared/components/NewWallet/Import/Import/Import.js, yarn.lock
=> chore(import): fix prop validation and update lockfile

src/renderer/shared/components/NewWallet/Ledger/Ledger.js, src/renderer/shared/components/NewWallet/Mnemonic/Mnemonic.js
=> chore(wallet): allow enter to submit form

src/renderer/shared/components/NewWallet/Ledger/Ledger.js, src/renderer/shared/components/NewWallet/Mnemonic/Mnemonic.js
=> chore(wallet): fix forms not submitting

.snyk
=> chore(.snyk): update snyk file

.circleci/config.yml, package.json, src/renderer/root/shapes/dialogShape.js
=> chore(app): deps

package.json, src/renderer/browser/components/RequestsProcessor/Send/index.js
=> [RELEASE] 0.6.6
