nos/client

src/components/AuthenticatedLayout/ButtonBar/ButtonBar.js, src/components/AuthenticatedLayout/Navigation/Navigation.js
At the hackathon some users were looking for the Settings button on the left menu. Since there are no page-specific settings right now, it makes sense to move it to the left menu.
https://github.com/nos/client/issues/87
Before:
After:
=> Move settings button to the left menu

src/components/Register/AccountDetails/SaveAccount/SaveAccount.js, src/components/Register/AccountDetails/SaveAccount/SaveAccount.scss, src/util/accountToNEP6.js
This PR adds the possibility for the users, after creating a new account via the client, to choose between saving this account as a new NP6 wallet (the only option available at the moment) or to add it to an already existing wallet (the feature this PR adds).
Currently, the users, after creating a new account via the registration page, can only choose to export the account by creating a new NP6. I think it would be nice to be able to add the account to a wallet of their choices.
Before: Only one button 'Save' was available on the account details page.
Now: Two buttons are available 'Save as new NEP6 Wallet' on the account details page.
Tested locally with:
- A wallet with 1+ accounts -> OK
- A wallet with 1 account -> OK
- A wallet with no account -> OK
- An empty file -> Error message …
=> feat(register): save the new account to an already existing Wallet file

public/electron.js, public/splash.html
Including a simple loader in the form-ish(-ish) of nOS logo. Further work to improve loader design would be desirable.
There were 2 main changes in the code:
public/electron.js (modification):
- mainWindow does not open as default anymore
- splashWindow was included to be quickly loaded while waiting for mainWindow
- when mainWindow finishes loading, capture by the "did-finish-load" event, then show mainWindow and destroys splashWindow
public/splash.html (new file):
- HTML code of the splash screen
- contains simple a loader
Related to issue #70 
No tests have been added besides running the ones currently available through `yarn run test`.
Fixes #
=> feat(public):add support for splash screen on app load

src/components/AuthenticatedLayout/AuthenticatedLayout.scss, src/components/Login/Login.scss, src/components/Register/Register.scss
This fixes focusing on inputs in the register screen.
The window drag and drop functionality is preventing users on Windows & Linux from focusing on the inputs in the register screen.  The cause is `-webkit-app-region: drag` eating mouse related events.  According to [this electron issue](https://github.com/electron/electron/issues/1354), the solution is to set `-webkit-app-region: no-drag` on any child elements that should accept normal mouse events.
I pinged two devs in the Discord `#develop` channel to ask them to try this branch.  One Windows user said it's fixed, another Gentoo Linux user said it's fixed.
N/A
Fixes #124
=> Fixed input focus not working on register screen

src/browser/actions/makeTestInvokeActions.js, src/browser/components/RequestsProcessor/TestInvoke/TestInvoke.js, src/browser/components/RequestsProcessor/TestInvoke/index.js, src/browser/shapes/resultStackShape.js, src/browser/shapes/testInvokeShape.js
testInvoke now returns the full result object instead of just the script.
* Give developers more info on their invocations (gas consumed)
* Allow developers that want to leverage the actual calculated result to do so
* Fired up the starter-kit, testInvoke now returns the result object. Validated that childs like `gas_consumed` and `stack` were present.
Fixes #
=> chore(api): return full result object instead of script

__tests__/components/App/Routes.test.js
This fixes React missing prop warnings.  The shape of the data in the browser reducer changed, but I neglected to update a test that stubs that data.
We shouldn't have test warnings, it implies our tests are not set up properly.
`yarn test`
N/A
=> Fixed React prop warnings in tests

package.json
This just changes the webpack dev server port from 3000 to 4000.
I keep having a lot of context switching (taking services down and up) between other work and nOS work.  There's some added overhead of having to switch things every time I want to work on nOS or work on something else.
It also seems like this change should not really have an impact on anyone else, so it feels like something that will make my life easier without negatively impacting anyone.  (Let me know if I'm wrong though!)
`yarn start` ran & loaded nOS as expected.
N/A
N/A
=> chore(dev): change default port from 3000 to 4000

src/root/stylesheets/global.scss
Changed the body background color
Removed the linear gradient from the body and replaced it with the color handled by the $content-bg-color variable
I spoke to @mhuggins on discord earlier and he suggested to start with a simple contribution by changing the 'the hideous green background'. 
Since my version of the client does not yet have the fix of the responsive tabs I managed to see the background color by adding multiple tabs that opened the overflow of the client
Before:
After:
Changed src/root/stylesheets/global.scss
Fixes #
=> chore(body): set background-color to content-bg

src/browser/components/Tabs/Tabs.js
Solving feature request #191 to add tab control.
This pull requests adds expected tab control to the nOS client.
Quick opening up tabs and closing current actives ones wasn't supported yet.
Tested on multiple OSX platforms and node environments.
N/A
#191
=> feat(tabs): shortcuts

src/browser/components/Tabs/Tabs.scss
Reverts nos/client#173
This breaks the app boundaries, adding scrollbars where we don't want them.
=> Revert "chore(browser): add responsive tab"

src/index.js
The `create-react-app` package includes a service worker to serve assets from local cache.  However, there is a conflict with using the `file:` protocol in conjunction with service workers in electron.
We're running into the issue found here: https://github.com/electron/electron/issues/9705
I asked @DalderupMaurice to try it on Windows.
Fixes #
=> Temporarily remove service worker included by CRA

__tests__/browser/index.test.js, src/browser/actions/browserActions.js, src/browser/components/Browser/Browser.js, src/browser/components/DAppContainer/DAppContainer.js, src/browser/components/DAppContainer/DAppContainer.scss, src/browser/components/DAppContainer/index.js, src/browser/components/Error/Error.js, src/browser/components/Error/Error.scss, src/browser/components/Error/index.js, src/browser/reducers/browserReducer.js
This PR implements the business logic required to show any type of error when a page could not be loaded (implementation of specific errors could be done in other PR's).
Take notice of Electron's errors https://cs.chromium.org/chromium/src/net/base/net_error_list.h
Currently when, particularly, nos:// domains couldn't be loaded it's unknown what's happening. The browsers shows an empty screen. To give the user some more insights about the error we would like to provide a custom `Error` component with more details (which target, error and description of the error).
Fixes #188
=> feat(error-page): add error page component

__tests__/register/components/AccountDetails/AccountDetails.test.js, src/register/components/AccountDetails/AccountDatum/AccountDatum.js, src/register/components/AccountDetails/AccountDetails.js
This removed the "passphrase" from the account details screen after registering.
Since the user enters their desired passphrase twice into two password fields, there's no reason to show the plaintext password on the next screen.
I smoke tested registering, ensured that saving a wallet still works as expected, and added a few component tests.
N/A
=> chore(register): passphrase removal

__tests__/browser/components/RequestsProcessor/GetBalance/index.test.js, src/renderer/browser/components/RequestsProcessor/ClaimGas/index.js, src/renderer/browser/components/RequestsProcessor/GetBalance/index.js, src/renderer/browser/components/RequestsProcessor/GetStorage/index.js, src/renderer/browser/components/RequestsProcessor/Invoke/index.js, src/renderer/browser/components/RequestsProcessor/Send/index.js, src/renderer/browser/components/RequestsProcessor/TestInvoke/index.js, src/renderer/browser/hocs/withRejectMessage.js
When using `withRejectMessage` HOC `error` prop will be made available if `Error` was thrown
#108
Tested in dApp template + updated test for `GetBalance`
closes #108
=> chore(error): propagate catched error as prop into withRejectMessage

src/main/index.js
This is a little urgent - due to the eslint PR, we introduced a bug, where the main window shows the splash screen, making the app not usable
read desc
👁 
Fixes #
=> chore(main): fixed rendering wrong window

src/renderer/shared/util/getBalances.js
Fixed token fetch across non-MainNet networks.
Token balances were fetching correctly for MainNet, but causing an error for other networks.  Although no tokens are being listed for other networks (due to not being listed in the [neo-tokens](https://github.com/CityOfZion/neo-tokens) repo), it's not resulting in a JS error.
Pulled up the "account" page on MainNet & TestNet.
N/A
=> chore(balances): fix token list across networks

package.json
Adds `webpack-dev-server` to greenkeeper ignore.
We have this package locked at a specific version that works with webpack 3.  We haven't upgraded to webpack 4 due to a number of issues outlined in other tracked github issues.
N/A
N/A
=> chore(package): add webpack-dev-server to greenkeeper ignore

src/renderer/browser/components/AddressBar/AddressBar.scss
This changes the styles of the navigation buttons so that they appear disabled.
The back, forward, reload, and notifications buttons don't do anything right now.  By making them respond to mouse events, it could confuse the user and have them wondering why the buttons aren't responding.
Hovered the mouse over the buttons.  (See screenshot.)
N/A
=> chore(browser): disabled styling for navigation buttons

src/renderer/browser/components/DAppContainer/DAppContainer.js
Fixes issue where a full screen error message was displaying for sub-resources (images, scripts, stylesheets, etc.) failing to load.
We only want to show an error message when the address bar's URI fails to loads.  Dependencies failing to load should not cause an issue.
1. Load https://bitsofco.de/styling-broken-images/ in nOS to ensure it loads without an error screen.
2. Load nos://fake.neo to ensure it shows an error screen.
Fixes #353
=> chore(browser): prevent page errors for sub-resources

__tests__/renderer/browser/actions/browserActions.test.js, __tests__/renderer/browser/reducers/browserReducer.test.js, src/renderer/browser/actions/browserActions.js, src/renderer/browser/reducers/browserReducer.js, src/renderer/logout/components/Logout/index.js
This ensures that the browser tabs are reset between authenticated sessions.
We want to work towards securing what users see within their own sessions.
1. Sign into an account.
2. Open two or more tabs.
3. Sign out & in again.
4. Observe tabs reset.
N/A
Fixes #343
=> feat(tabs): reset on logout

src/renderer/account/components/SendPanel/SendPanel.js, src/renderer/account/components/SendPanel/SendPanel.scss, src/renderer/login/components/LoginFormPassphrase/LoginFormPassphrase.scss, src/renderer/register/components/RegisterForm/RegisterForm.scss, src/renderer/shared/components/Forms/Button/Button.scss, src/renderer/shared/components/Forms/Input/Input.scss, src/renderer/shared/components/Forms/Select/Select.scss
This cleans up the new button styles in a few ways:
* antialiases the labels to better match designs
* makes them `inline-block` instead of `block` by default
* adds a `not-allowed` cursor for disabled buttons
Some of the styles and behavior didn't look right compared to designs.
Opening the screens that have buttons and ensuring they match expectations.
N/A
=> chore(button): cleanup

src/renderer/account/components/SendPanel/index.js
This adds the current network as a prop to the SendPanel, which is needed to successfully transfer assets & tokens.
While refactoring the account screen to implement the new designs, I accidentally removed a call needed to inject the current network as a prop into the `SendPanel` component.
Sending NEO on TestNet.
N/A
=> chore(send): restore network for sending assets/tokens

__tests__/renderer/browser/components/DAppContainer/DAppContainer.test.js, src/renderer/browser/components/DAppContainer/DAppContainer.js, src/renderer/browser/components/DAppContainer/index.js
Links that should open in a new window/tab now open in the nOS client instead of the default browser.
nOS should more or less behave like a normal browser, but with advanced blockchain functionality.  Opening a new window/tab in a different browser doesn't match that expectation.
* Click on links with a `target="_blank"` attribute.
* Cmd+clicking links without a `target` attribute.
Fixes #374
=> chore(browser): open new windows/tabs in nos client

src/renderer/account/components/AccountPanel/Breakdown/SectionLabel/SectionLabel.scss, src/renderer/root/components/AuthenticatedLayout/Tab/Tab.scss
This updates the browser tabs to match the designs.
It was difficult to see where one tab stopped and another started prior to this change.
Opening 3+ tabs and switching between them.
N/A
=> chore(browser): add tab separators

src/renderer/browser/components/DAppContainer/DAppContainer.js
This is a small quality of life change to:
1. ensure that when the nOS client window loses and regains focus, the current webview also regains focus, and
2. automatically focus the webview when a page is finished loading.
Currently, if a user has a text input (for example) focused in a webpage, and they go to another window to copy something before Alt+Tabbing back to the client, the input they had focused is no longer focused.  Pasting requires another mouse click or tabbing to the element again.
Similarly, when a webpage loads, if the site deems that an input should be autofocused, that doesn't happen since the webview does not have focus.
* Loading pages that have inputs with autofocus (e.g.: https://google.com).
* Opening sites in two tabs, focusing inputs in each, and switching tabs …
=> feat(browser): restore webview focus when window is focused

src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.scss
This fixes an unintentional stoke width being applied to the sidebar links.  It also removes some focus coloration that doesn't match the designs.
@deanpress has pixel-perfect vision.
Smoke testing.
N/A
=> chore(sidebar): fixed navigation icon stoke width

src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.scss
This fixes the layout between the browser tabs and browser itself.
When the client is shrunk to a very small height, the tab bar gets squished, and there's an unwanted overlap between the browser tabs and the browser itself.
Resizing the browser window so it's very short.
**Before:**
**After:**
N/A
=> chore(layout): fixed sizing for small windows

src/renderer/account/components/TransactionsPanel/Receive/Receive.js, src/renderer/account/components/TransactionsPanel/Send/Send.js, src/renderer/login/components/LoginFormLedger/LoginFormLedger.js, src/renderer/login/components/LoginFormPassphrase/LoginFormPassphrase.js, src/renderer/login/components/LoginFormWIF/LoginFormWIF.js, src/renderer/login/components/LoginFormWalletFile/LoginFormWalletFile.js, src/renderer/register/components/AccountDetails/SaveAccount/SaveAccount.js, src/renderer/register/components/RegisterForm/RegisterForm.js, src/renderer/settings/components/NetworkSettings/NetworkSettings.js, src/renderer/shared/components/Alert/Alert.js, src/renderer/shared/components/Confirm/Confirm.js, src/renderer/shared/components/Confirm/Confirm.scss, src/renderer/shared/components/Forms/Button/Button.scss, src/renderer/shared/components/Forms/PrimaryButton/PrimaryButton.js, src/renderer/shared/components/Forms/PrimaryButton/PrimaryButton.scss, src/renderer/shared/components/Forms/PrimaryButton/index.js
* Adds a PrimaryButton component, which reflects the existing button styles.
* Updates the Button component to represent secondary actions.
* Smooths the primary button background color to match designs
* Uses `React.forwardRef` to forward refs to the raw DOM element, which prevents us from having to manually implement component functions like `focus` and `blur`.
Designs have primary and secondary buttons, this brings the styles inline with design.
Smoke testing.
N/A
=> chore(button): primary & secondary styles

src/renderer/root/stylesheets/global.scss, src/renderer/shared/components/Forms/Button/Button.scss, src/renderer/shared/components/Tabs/Tabs.scss
This updates the interface to use the default mouse cursor (rather than the hand/link cursor) everywhere.  It also makes it so that the user can't highlight text in the UI.
These changes do not apply to any content loaded in a webview, where it still behaves like a normal browser.
The UI interactions should behave like a native app, not a web app.
Moving and clicking/dragging the mouse cursor over components in the UI.
N/A
N/A
=> chore(ui): native user interactions

__tests__/renderer/shared/hocs/withUnmountReset.test.js, src/renderer/register/components/Register/index.js, src/renderer/register/components/RegisterForm/index.js, src/renderer/shared/hocs/withUnmountReset.js
This fixes account creation to ensure the correct details are displayed to the user.  Previously, if two subsequent accounts were created, the details of the first one would continue to render instead of the new information.
Newly created account data should be secure, and so it shouldn't be persisted between creations.  The app should also properly reflect the correct information for any use case such as account creation.
Smoke tested by creating multiple subsequent accounts.  Also added tests.
Fixes #427
=> chore(register): clean store between account creations

src/common/stylesheets/mixins.scss, src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.scss, src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.js, src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.scss, src/renderer/root/components/AuthenticatedLayout/TabLink/TabLink.js, src/renderer/root/components/AuthenticatedLayout/TabLink/TabLink.scss, src/renderer/root/components/AuthenticatedLayout/TabLink/index.js
This adds highlighting to the active navigation link.  It also moves the logout link to the bottom of the sidebar & hides the dApp link (for now).
Matches designs.
Navigating between links both via the sidebar links and via already opened tabs.
Fixes #405
=> chore(navigation): highlight active & focused links

src/renderer/root/components/AuthenticatedLayout/AddressBar/AddressBar.scss, src/renderer/root/components/AuthenticatedLayout/Tab/Tab.scss
This fixes tabs appearing above the page overlay when displaying modals.
A z-index was being used on the `AddressBar` component to prevent its drop-shadow from extending upward onto the `Tabs` above it.  This had an unintended effect of displaying it above everything else since nothing else had a z-index property.  To fix it, I replaced it with the `clip-path` property, which is kind of like a bounded `overflow` region.
Smoke testing on macOS and observing now shadow extending above the active tab.
N/A
Fixes #368
=> chore(tabs): replaced z-index with clip-path

.stylelintrc, package.json, src/renderer/settings/components/GeneralSettings/GeneralSettings.scss, src/renderer/settings/components/SectionContent/SectionContent.scss, src/renderer/settings/components/Settings/Settings.js, src/renderer/settings/components/Settings/Settings.scss, src/renderer/settings/components/SidebarLink/SidebarLink.js, src/renderer/settings/components/SidebarLink/SidebarLink.scss, src/renderer/settings/components/SidebarLink/index.js, src/renderer/shared/components/Page/Page.js, yarn.lock
This implements the sidebar navigation from the designs.
* The sidebar links are clickable, and if the section is off the screen, will smoothly scroll into view.
* The sidebar will automatically highlight the section that is active when scrolling.
* The sidebar links are sticky so as to not be lost when scrolling.
* The settings screen is responsive and will hide the sidebar for narrow windows.
Implement new designs.
Smoke testing.
Fixes #403
=> feat(settings): sidebar navigation

config/webpack.renderer.js, src/renderer/account/components/AccountPanel/Breakdown/Breakdown.js
This fixes an issue with the distributable version (via `yarn dist`) that caused the app crash when opening the Account screen.
The app crashes when trying to render the breakdown chart with 3+ tokens.  The error is:
> TypeError: Assignment to constant variable.
This is caused by the uglify plugin inlining single-use functions, as discovered here: https://github.com/mishoo/UglifyJS2/issues/2842#issuecomment-359722583
1. Use `yarn dist` to create a distributable version of the app.
2. Run the app, and login with an account that has 3+ distinct token balances.
3. Observe the app "crash" (HTML output disappears).
N/A
=> chore(account): fixed TypeError for accounts with 3+ tokens

config/webpack.renderer.js
Fixes `yarn start`.
Although #455 fixed an issue with `yarn dist`, it altogether broke `yarn start`.  This updates that webpack config change to ensure it's only applied when appropriate.
Both `yarn dist` and `yarn start`
N/A
N/A
=> chore(webpack): fixed development build

src/common/stylesheets/mixins.scss, src/renderer/account/components/TransactionsPanel/Receive/Receive.scss, src/renderer/account/components/TransactionsPanel/Send/Send.scss, src/renderer/account/components/TransactionsPanel/TransactionsPanel.scss, src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.scss, src/renderer/settings/components/NetworkSettings/NetworkSettings.scss
This updates the settings & account tabs to treat the mouse cursor and user selection like a normal browser.
Anything that renders within a tab should behave like web content.
Smoke testing buttons, tabs, etc. between login screen vs. account & settings tabs.
N/A
Fixes #450
=> chore(style): treat tabbed content like web ux

src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.js
Restores the "DApps" link in the sidebar, but makes it disabled.
@deanpress felt that the sidebar looked too barren without it, and also wants users to be able to see what features to expect.
Smoke testing.
N/A
=> chore(nav): restore dapps link

__tests__/renderer/shared/components/Forms/Input/index.test.js, __tests__/renderer/shared/components/Forms/Label/index.test.js, __tests__/renderer/shared/components/Forms/LabeledInput/index.test.js, __tests__/renderer/shared/components/Forms/LabeledSelect/index.test.js, __tests__/renderer/shared/components/Forms/Select/index.test.js, src/renderer/account/components/TransactionsPanel/Send/Send.js, src/renderer/login/components/LoginFormPassphrase/LoginFormPassphrase.js, src/renderer/login/components/LoginFormWIF/LoginFormWIF.js, src/renderer/login/components/LoginFormWalletFile/LoginFormWalletFile.js, src/renderer/register/components/AccountDetails/SaveAccount/SaveAccount.js, src/renderer/register/components/RegisterForm/RegisterForm.js, src/renderer/settings/components/NetworkSettings/NetworkSettings.js, src/renderer/shared/components/Forms/Input/Input.js, src/renderer/shared/components/Forms/Input/Input.scss, src/renderer/shared/components/Forms/Label/Label.js, src/renderer/shared/components/Forms/Label/Label.scss, src/renderer/shared/components/Forms/Label/index.js, src/renderer/shared/components/Forms/LabeledInput/LabeledInput.js, src/renderer/shared/components/Forms/LabeledInput/LabeledInput.scss, src/renderer/shared/components/Forms/LabeledInput/index.js, src/renderer/shared/components/Forms/LabeledSelect/LabeledSelect.js, src/renderer/shared/components/Forms/LabeledSelect/LabeledSelect.scss, src/renderer/shared/components/Forms/LabeledSelect/index.js, src/renderer/shared/components/Forms/Select/Select.js, src/renderer/shared/components/Forms/Select/Select.scss
This breaks the existing `Input` and `Select` components apart so that the labels are no longer embedded within them.  Two new components -- `LabeledInput` and `LabeledSelect` -- provide the functionality that these were providing before.
While working on the new select component (from the new designs), I found that I needed to reuse the `Input` component with custom styling, but having it wrapped in a label made that difficult.  This lays the groundwork for that use case without breaking any existing implementation.
Smoke tested forms throughout the app & added some basic component tests.
N/A
N/A
=> chore(form): separate label into its own component

.codecov.yml, README.md, __tests__/renderer/shared/components/Forms/Input/Input.test.js, __tests__/renderer/shared/components/Forms/Input/index.test.js, __tests__/renderer/shared/components/Forms/LabeledInput/LabeledInput.test.js, __tests__/renderer/shared/components/Forms/LabeledInput/index.test.js, __tests__/renderer/shared/components/Forms/LabeledSelect/LabeledSelect.test.js, __tests__/renderer/shared/components/Forms/LabeledSelect/index.test.js, __tests__/renderer/shared/components/Forms/Select/Select.test.js, __tests__/renderer/shared/components/Forms/Select/index.test.js, __tests__/setupFramework.js, package.json, src/renderer/shared/components/Forms/Button/Button.js, src/renderer/shared/components/Forms/Button/index.js, src/renderer/shared/components/Forms/Input/Input.js, src/renderer/shared/components/Forms/Input/index.js, src/renderer/shared/components/Forms/LabeledInput/LabeledInput.js, src/renderer/shared/components/Forms/LabeledInput/index.js, src/renderer/shared/components/Forms/LabeledSelect/LabeledSelect.js, src/renderer/shared/components/Forms/LabeledSelect/index.js, src/renderer/shared/components/Forms/PrimaryButton/PrimaryButton.js, src/renderer/shared/components/Forms/PrimaryButton/index.js, src/renderer/shared/components/Forms/Select/Select.js, src/renderer/shared/components/Forms/Select/index.js, src/renderer/shared/hocs/withForwardedRef.js
~~**NOTE:** This PR is blocked until https://github.com/airbnb/enzyme/issues/1604 is fixed via https://github.com/airbnb/enzyme/pull/1592.~~
This updates our form-based components to forward refs to the actual DOM element.  This makes it so that the component does not need to expose functions specific to any element (e.g.: `focus()`, `blur()`, `value`).
Components should behave in an intuitive manner.
Via the test suite and smoke testing.
N/A
N/A
=> chore(forms): forward component refs to DOM elements

__tests__/renderer/shared/components/Forms/LabeledInput/index.test.js, __tests__/renderer/shared/components/Forms/LabeledSelect/index.test.js
This fixes some test warnings due to missing props.
Unnecessary warnings make it hard to scan & parse test output.
Running `yarn test`.
N/A
N/A
=> chore(tests): fixed missing prop warnings

package.json, yarn.lock
The redux 4.0.0 upgrade broke the app -- it just shows a white screen instead of the login form.
We tried upgrading redux to 4.0.0 and removing it from the greenkeeper ignore in package.json, but it didn't work out.
Running the app.
N/A
=> chore(package): revert redux upgrade

package.json, yarn.lock
<details>
<summary>Release Notes</summary>
<strong>v3.0.0</strong>
<p>Update packages which results in drop of support for Node 4.</p>
<p>V3+ requires node 6+</p>
<p>Updated:</p>
<ul>
<li>mocha@5.2.0</li>
<li>expect replaced with expect-legacy@1.20.2 (later expect doesn't support mocha, only jest)</li>
<li>core-js@2.5.7</li>
<li>joi@13.0.0</li>
<li>request@2.88.0</li>
</ul>
</details>
<details>
<summary>Commits</summary>
<p>The new version differs by 2 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/jeffbski/wait-on/commit/5e92e511e13da4c846b0ee5f8b556e8517cc7643"><code>5e92e51</code></a> <code>3.0.0</code></li>
<li><a href="https://urls.greenkeeper.io/jeffbski/wait-on/commit/2ff1c15dc99c1b076bb9ea46d024c7342c5ad139"><code>2ff1c15</code></a> <code>update packages from …
=> Update wait-on to the latest version 🚀

src/renderer/browser/components/DAppContainer/DAppContainer.js
Fixes an issue where a URL change within an IFRAME caused the browser address to change.  This should only happen when the main frame URL changes.
We want the browser aspect to work as expected.
Do a google search for anything.  Wait a few seconds, and the address bar will change to something under the "notifications.google.com" subdomain.
N/A
=> chore(browser): fix iframe navigate-in-page updating url

__tests__/renderer/browser/util/parseURL.test.js, package.json, src/renderer/browser/util/parseURL.js, yarn.lock
This makes non-URI entries in the address bar behave as Google searches.  In the future, we can allow customizing the search engine.
When the user enters something into the address bar that is not a valid URI, we should treat it as a search query.
Adding tests and smoke testing.
Fixes part of #371.
=> feat(browser): perform search for non-URI queries

src/renderer/login/components/LoginFormWalletFile/LoginFormWalletFile.js
Similar to #497, this is a very minor fix such that when opening a wallet file for login via NEP2, the dialog is attached to the window.
I noticed that the "Select Wallet File" dialogs was not attached to the window, but was instead free-floating.
Selecting a wallet file to use to login.
N/A
=> chore(login): select wallet file dialog context

src/main/index.js
This prevents the app from seemingly reloading the first time the confirmation modal is displayed.
https://github.com/nos/client/issues/340#issuecomment-414095942
Sending an asset through the account screen.
N/A
Fixes #340
=> chore(send): prevent reload

__tests__/renderer/browser/components/RequestsProcessor/GetAddress/index.test.js, __tests__/renderer/browser/components/RequestsProcessor/GetLastBlock/GetLastBlock.test.js, __tests__/renderer/browser/components/RequestsProcessor/GetLastBlock/index.test.js, __tests__/renderer/root/components/AuthenticatedLayout/LastBlock/LastBlock.test.js, src/renderer/browser/components/RequestsProcessor/GetLastBlock/GetLastBlock.js, src/renderer/browser/components/RequestsProcessor/GetLastBlock/index.js, src/renderer/browser/components/RequestsProcessor/mappings.js, src/renderer/root/components/AuthenticatedLayout/LastBlock/LastBlock.js, src/renderer/root/components/AuthenticatedLayout/LastBlock/LastBlock.scss, src/renderer/settings/components/NetworkSettings/index.js, static/preloadRenderer.js
**NOTE**: Do not merge until #521 has been merged.  This builds off that PR.  This PR will need to be updated to set the target branch to `develop` before merging.
This adds a `getLastBlock` API function for dApps.
dApps may want to request the latest block data.  An example is what @jeroenptrs is working on.
Opening the inspector on a webview, and calling:
```js
window.NOS.V1.getLastBlock().then(function(block) { console.log(block) })
```
N/A
=> feat(api): added getLastBlock api function

src/renderer/root/components/AuthenticatedLayout/LastBlock/LastBlock.js
The calculation for the block time in local time was incorrect.  We need to convert seconds to milliseconds first.
Block time is not displaying correctly in the new sidenav tooltip.
Displaying the tooltip and comparing to my computer clock.
N/A
=> chore(block): fixed local block time

src/renderer/browser/values/browserValues.js, src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.js, src/renderer/shared/images/icons/exchange.svg
Adds "Exchange" sidebar link.
We want users to know that exchange functionality will be coming in the future.
Logged in, saw the icon, hovered the mouse, tried clicking.
N/A
=> chore(nav): add exchange sidebar link

src/renderer/root/components/AuthenticatedLayout/index.js, src/renderer/shared/hocs/withProgressChange.js, src/renderer/shared/util/notifyWebviews.js, static/preloadRenderer.js
Adds `on`, `off`, and `once` API functions to subscribe to events.  Added one event for new blocks being received.
We want dApps to be aware of events pertaining to the NEO ecosystem.
Used the webview console to subscribe & unsubscribe.
Fixes #54.
=> feat(api): events api for blocks

src/renderer/root/components/AuthenticatedLayout/ExplorerLink/ExplorerLink.js, src/renderer/root/components/AuthenticatedLayout/ExplorerLink/index.js, src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.js, src/renderer/root/components/AuthenticatedLayout/TabLink/TabLink.js
This links the block side nav item to the block in neoscan.  Unfortunately, this probably won't work since neoscan is always at least one block behind the current block height.
Dean requested as part of #527.
Clicking the link and navigating to neoscan.
Fixes #527.
=> feat(block): open block in neoscan tab

src/renderer/shared/components/Tooltip/Tooltip.js
This PR sets the mouse-leave delay to 0s when hiding tooltips.
This is an incremental improvement to the tooltip behavior.  By default, rc-tooltip has a 0.1s delay before hiding an element.  The impact is that multiple tooltips are visible at the same time, even if only momentarily.  Preferably, we only show a single tooltip at a time.
Hovering the mouse over side navigation icons quickly.
N/A
=> chore(tooltip): remove mouse leave delay

__tests__/renderer/root/components/Layout/AuthenticatedLayout/AuthenticatedLayout.test.js, src/renderer/account/components/Account/index.js, src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.js, src/renderer/root/components/AuthenticatedLayout/index.js
This adds automatic refreshing for account balances whenever a new block is received.
The account screen currently does not update and has no mechanism for updating, not even when sending assets.
* Opened the account screen, and observed a single balances data fetch.
* Watched for new blocks being successfully received in redux store.
* Observe balances data re-fetch.
* Ensure that account screen doesn't change to "Loading" messaging between fetching.
* Ensure that account screen does change to "Loading" messaging when changing networks.
Fixes #475.
=> feat(balance): update balances on new blocks

static/preloadRenderer.js
This fixes an issue I accidentally introduced as part of #530.  nOS API functions were not being resolved or rejected due to IPC listeners unsubscribing early.
This is a core feature of the app that has to work.
Called directly from the browser console:
```js
window.NOS.V1.getAddress().then(alert).catch(alert);
```
N/A
=> chore(api): fixed ipc early unsubscribe

.circleci/config.yml
This adds a missing piece to the CircleCI config so that win32 binaries get built.
We had the steps in there, but we weren't kicking it off.
It hasn't, no one has a win32 machine.
N/A
=> chore(ci): fixed win32 deploy

src/main/util/bindMenus.js
Fixed an error caused by reloading while on the account or settings pages.
Reload/back/forward don't work while on the account or settings pages.
Pressing reload button while on the account or settings screen.
Fixes #547.
=> chore(menu): fixed reload button error for account/settings

package.json
This fixes our test suite hanging on CI.
> An alternative to expediting test execution time on Continuous Integration Servers is to set the max worker pool to ~4.
https://jestjs.io/docs/en/troubleshooting.html#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server
Building on CI.
N/A
=> chore(ci): limit workers

src/renderer/shared/components/Forms/Input/Input.js, src/renderer/shared/components/Forms/Input/Input.scss, src/renderer/shared/components/Forms/Label/Label.js, src/renderer/shared/components/Forms/Label/Label.scss, src/renderer/shared/components/Forms/LabeledInput/LabeledInput.js, src/renderer/shared/components/Forms/LabeledSelect/LabeledSelect.js, src/renderer/shared/components/Forms/Select/Select.js, src/renderer/shared/components/Forms/Select/Select.scss
This adds the disabled input state per the designs.
Adds clarity in some places.  We're also going to show some disabled states around the priority fee settings.
Visually.
N/A
=> feat(forms): disabled input states

src/main/util/bindMenus.js
This fixes the "Reload" menu accelerator (shortcut key).
A simple typo prevented Cmd+R / Ctrl+R from working for reloading the page.
Loading a webpage, then pressing Cmd+R.
N/A
=> chore(menu): fix reload accelerator

src/renderer/root/components/AuthenticatedLayout/FavIcon/FavIcon.js, src/renderer/root/components/AuthenticatedLayout/FavIcon/FavIcon.scss, src/renderer/root/components/AuthenticatedLayout/FavIcon/index.js, src/renderer/root/components/AuthenticatedLayout/Tab/Tab.js, src/renderer/root/components/AuthenticatedLayout/Tab/Tab.scss, src/renderer/root/components/AuthenticatedLayout/Tabs/Tabs.js, src/renderer/shared/images/browser/favicon-nos.svg
This updates the account and settings tabs to use the nOS icon as the favicon.
Using the nOS icon to highlight nOS content will help the to distinguish it from other tabs.
Opening the account and settings tabs, as well as other websites.
N/A
=> chore(favicon): use nos favicon for internal links

__tests__/renderer/browser/util/validateInvokeArgs.test.js, __tests__/renderer/login/actions/authActions.test.js, src/renderer/browser/actions/makeInvokeActions.js, src/renderer/browser/components/RequestsProcessor/Invoke/index.js, src/renderer/browser/components/RequestsProcessor/RequestProcessor.js, src/renderer/browser/components/RequestsProcessor/mappings.js, src/renderer/browser/hocs/withInvocationPrompt/index.js, src/renderer/browser/hocs/withSignTransactionToast.js, src/renderer/browser/util/validateInvokeArgs.js, src/renderer/login/actions/authActions.js, src/renderer/login/util/ledger.js
Adds Ledger support for invocation transactions.
**Note:** There is a bug with two toasts displaying instead of one that I haven't figured out yet.  I'll figure this out as a follow-up to this PR since it's pretty minor.
Ledger users cannot currently complete invocation transactions successfully.
1. Log in with Ledger.
2. Open a create-react-app app that defines an invocation.
3. Click "Confirm" in the invocation prompt.
4. Sign or decline the transaction on the Ledger device.
Fixes #560.
=> feat(ledger): sign invocations

__mocks__/electron.js, src/main/util/bindMenus.js, src/renderer/root/components/AuthenticatedLayout/AddressBar/AddressBar.js, src/renderer/root/components/AuthenticatedLayout/Tabs/Tabs.js, src/renderer/shared/components/Forms/Input/Input.js
This removes the old code for opening/closing tabs, and replaces it with some menu items & shortcut keys.
* Open Tab (Cmd+T or Ctrl+T)
* Close Tab (Cmd+W or Ctrl+W)
* Open Location (Cmd+L or Ctrl+L) focuses the address bar
* Escape key cancels any changes within the address bar
* Cmd+(1-8) or Ctrl+(1-8) to jump to tabs 1-8
* Cmd+9 or Ctrl+9 to jump to last tab
* Windows mouse button shortcuts for back, forward, & close tab
Making the app behave in more standard ways.
Using the menu items with both the mouse and the keyboard.
Fixes #341.
=> feat(menu) open tab, open location, close tab, & shortcut keys

src/main/util/bindMenus.js, src/renderer/root/components/AuthenticatedLayout/Tabs/Tabs.js, src/renderer/root/components/AuthenticatedLayout/Tabs/index.js, src/renderer/root/components/LoginLayout/LoginLayout.js
The "Learn More" menu item in the "Help" menu (mac only) was being opened in an external browser.  Since nOS can behave as a browser, we should open it in there.  The only time we can't is when the user hasn't logged in yet, in which case we continue to open via shell (default browser).
nOS is a browser, let's use it.
* Clicking the menu item while at the login screen & when logged in.
* Opening new tabs via Cmd+T & the `+` icon in the tab bar.
N/A
N/A
=> chore(menu): open help link in nOS when possible

src/main/index.js, src/main/util/bindContextMenu.js
This restores the context menus for input elements throughout the app.
I unintentionally removed this logic as part of #538.
Right clicking various inputs (text, password, etc.)
N/A
Fixes #614
=> chore(menu): restore context menus

static/preloadRenderer.js
This adds `window.NOS.version` so that dApps can know what version of nOS is being used.
Useful for knowing what functionality is available.  Pertains to the ICO.
Chrome inspector console.
N/A
=> feat(api): add version constant

src/renderer/settings/actions/versionActions.js, src/renderer/settings/components/Settings/Settings.js, src/renderer/settings/components/Settings/Settings.scss, src/renderer/settings/components/Version/Version.js, src/renderer/settings/components/Version/Version.scss, src/renderer/settings/components/Version/index.js, src/renderer/shared/components/Loading/Loading.js
This adds the current & latest available versions of the nOS client to the settings screen.
@deanpress This will be useful to provide clarity for instructions directing users how to check if they have the latest version needed for ICO.
The user should have an easy way to check the app version.
Opening the settings page, clicking the button links.
N/A
=> feat(settings): show current and latest versions

package.json, src/renderer/account/components/TransactionsPanel/Receive/Receive.js, src/renderer/register/components/AccountDetails/AccountDatum/AccountDatum.js, yarn.lock
This updates the react-copy-to-clipboard dependency to an nos published fork.
Building the dependency from GitHub wasn't working properly for Windows. 👊
Copying account details from registration screen.
N/A
=> chore(copy): replace react-copy-to-clipboard with nos fork

src/renderer/settings/components/Version/Version.js
Fixes an SVG size flicker when the settings screen loads for the first time.
Jarring experience.
Loading the settings screen.
https://gyazo.com/1b98aa48b3a2ca6dfc1d4f9912b45d40
N/A
=> chore(version): fix svg flicker on settings screen load

src/common/stylesheets/mixins.scss, src/renderer/root/components/AuthenticatedLayout/AddressBar/AddressBar.js, src/renderer/root/components/AuthenticatedLayout/AddressBar/AddressBar.scss, src/renderer/root/stylesheets/global.scss, src/renderer/shared/components/Forms/Button/Button.scss, src/renderer/shared/components/Forms/Select/Select.scss, src/renderer/shared/components/Tabs/Tabs.scss
Restores the mouse cursor to the "pointer" style on buttons and form elements throughout the app.
It can be hard to determine if the user has the cursor over clickable elements in some instances.
Navigating throughout the app and hovering the mouse over things.
N/A
=> chore(ux): restore mouse cursors throughout app

src/renderer/account/components/AccountPanel/AccountPanel.scss, src/renderer/account/components/AccountPanel/Breakdown/Breakdown.js, src/renderer/account/components/AccountPanel/Breakdown/Breakdown.scss, src/renderer/account/components/AccountPanel/Breakdown/BreakdownChart/BreakdownChart.js, src/renderer/account/components/AccountPanel/Breakdown/BreakdownChart/BreakdownChart.scss, src/renderer/account/components/AccountPanel/Breakdown/BreakdownChart/index.js, src/renderer/account/components/AccountPanel/Breakdown/SectionLabel/SectionLabel.js, src/renderer/account/components/AccountPanel/Breakdown/SectionLabel/SectionLabel.scss, src/renderer/account/components/AccountPanel/Breakdown/TotalValue/TotalValue.js, src/renderer/account/components/AccountPanel/Breakdown/TotalValue/TotalValue.scss, src/renderer/account/components/AccountPanel/Breakdown/TotalValue/index.js, src/renderer/account/components/AccountPanel/Breakdown/index.js, src/renderer/account/util/calculateTokenValue.js
This improves the breakdown chart in a few ways:
* Prevents the labels from being cut off around edges of chart
* Renders "primary holding" token icon in middle of chart
* Moves "total value" above chart
There have been some complaints about the chart, and we've had improved designs for awhile.  This gets us closer.
Opening the account screen for various accounts.
Fixes #409
=> feat(account): breakdown chart improvements

src/renderer/account/components/Account/Account.js, src/renderer/account/components/Account/Account.scss, src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.scss
Prevents unnecessary scrollbar from displaying on the account screen.
Scrolling implies there is more to see, but there isn't, which could be confusing.
Testing scrolling throughout all pages when scrollbar should and should not appear.
N/A
Fixes #597
=> chore(account): prevent unnecessary scrolling

src/renderer/browser/util/bindContextMenu.js
Fixes the "Inspect Element" context menu option in the nOS distributable.
The menu option was only rendering in development.  To force it in production, the value must be explicitly set to true.
Running `yarn dist`, opening the executable, and right clicking on a website.
N/A
=> chore(menu): fixed Inspect Element not displaying in prod

package.json, yarn.lock
- The `devDependency` [eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest) was updated from `21.24.2` to `21.26.2`.
[Update to this version instead 🚀](https://github.com/nos/client/compare/develop...nos:greenkeeper%2Feslint-plugin-jest-21.26.2) 
<details>
<summary>Release Notes for v21.26.2</summary>
<h2><a href="https://urls.greenkeeper.io/jest-community/eslint-plugin-jest/compare/v21.26.1...v21.26.2">21.26.2</a> (2018-10-26)</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>no-focused-tests:</strong> detect usage like 'fit.each()' (<a href="https://urls.greenkeeper.io/jest-community/eslint-plugin-jest/commit/63e6818">63e6818</a>), closes <a href="https://urls.greenkeeper.io/jest-community/eslint-plugin-jest/issues/188" data-hovercard-type="issue" …
=> Update eslint-plugin-jest to the latest version 🚀

src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.js
Changes polling frequency from 10 sec to 14 sec.
There's no reason to poll every 10 seconds since block time is at ~15 seconds.  By polling one sec less often than that, we should typically see each new block come in with minimal impact.
Running the client and observing console + current block in sidebar nav.
N/A
N/A
=> chore(block): change polling frequency from 10 to 14 sec

src/renderer/shared/util/getBalances.js, src/renderer/shared/util/getTokens.js
This changes the way we fetch token balances to stuff as many `balanceOf` calls as possible into each test invocation.
We're flooding RPC nodes with requests, and users are being rate limited.
Watching `console` log lines and network calls to observe frequency of calls.
N/A
N/A
=> feat(balance): chunk nep5 balance calls

src/renderer/account/components/AccountPanel/AccountPanel.scss
Fixed centering for the primary holding token icon.
It's overlapping things when the user has many tokens.
Opening the account screen for an account with many tokens, resized the window.
N/A
=> chore(balance): fix token icon centering

src/renderer/account/components/Account/index.js, src/renderer/account/components/AccountPanel/Holdings/index.js, src/renderer/shared/values/assets.js
Ensures that NOS token is always displayed, even if it's 0 balance, and sorts it to the top of the list.
To provide users a way of understanding that NOS exists as a token.
Viewing an account screen for an account with zero balance.
N/A
=> feat(balance): sort nos token first

src/renderer/account/components/AccountPanel/TokenBalance/TokenBalance.js
Localizes the token amount for the user.
It can be difficult to scan/parse the token holding amount due to lack of commas (or whatever your locale uses).
Looking at the holdings.
N/A
=> chore(account): localize token balances in holdings

__tests__/renderer/browser/components/RequestsProcessor/Send/index.test.js, src/renderer/browser/actions/makeInvokeActions.js, src/renderer/browser/actions/makeSendActions.js, src/renderer/shared/util/claimGas.js, src/renderer/shared/util/sendAsset.js
This adds the same NEO RPC node selection logic to sendAsset and doInvoke calls.
This was intended to be used for all RPC calls, but some were missed due to different scenarios in logic.
It hasn't yet.  We'll need to send assets and invoke to ensure things still work properly.
N/A
=> chore(rpc): node selection for sendAsset and doInvoke

src/renderer/root/components/AuthenticatedLayout/Navigation/Navigation.scss
This prevents the window from scrolling when it's too short.
This was happening when the navigation icons in the sidebar extend beyond the window height.
Shrinking the window & trying to scroll.
N/A
N/A
=> chore(layout): prevent window scrolling

package.json, renovate.json, yarn.lock
This reverts the electron-is-dev upgrade PR that was merged in.  The 1.x series works with Electron 3, but we're stuck on Electron 2.  Without this revert, `isDev` returns `true` in the distributable version, and the app won't start since it can't find some dev dependencies.
The app should build.
`yarn dist`
N/A
N/A
=> chore(deps): revert electron-is-dev upgrade

static/preloads/api.js
exported the api properly
It's needed
Manually
Fixes #
=> chore(static): export API properly

src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.scss
Fix unintended scrolling
- side nav was not extended
- internet tabs etc were scrollable
displaced the UI
Before
After
Fixes #747
=> chore(authLayout): fix unintended scrolling

src/renderer/root/components/AuthenticatedLayout/Tab/Tab.js, src/renderer/root/components/AuthenticatedLayout/Tabs/Tabs.js
close tab on middle mouse btn
#713 
Fixes #713
=> feat(tabs): close tab on middle mouse btn

src/renderer/root/components/AuthenticatedLayout/Tabs/Tabs.js
exit client when hitting middle mouse on last tab
it did refresh the page instead of closing it
manually
Fixes #
=> feat(tabs): exit client when closing last tab w/ middle mouse

src/main/index.js, src/main/util/registerNosProtocol.js, static/splash.html
check for updates during splashscreen and added user feedback in the splash screen
This prevents the client from starting during downloading/installing the client which might make users think it's crashing
manually
Fixes #
=> chore(autoUpdates): check for updates during splashscreen and added user feedback

src/renderer/settings/actions/networksActions.js
Fixes a network issue
It removed the custom networks
manually
Fixes #356
=> chore(networks): fix network issue

src/renderer/root/components/App/index.js, src/renderer/settings/components/NetworkSettings/NetworkSettings.js
fix network reselection on startup
It selected incorrectly
Fixes https://github.com/nos/client/issues/899
=> chore(network): fix network reselection on startup

__tests__/renderer/register/components/AccountDetails/AccountDetails.test.js, src/renderer/browser/components/Browser/Browser.js, src/renderer/login/actions/previousAuthActions.js, src/renderer/login/components/Login/Login.js, src/renderer/login/components/Login/Login.scss, src/renderer/login/components/LoginFormPassphrase/index.js, src/renderer/login/components/LoginFormProfile/LoginFormProfile.js, src/renderer/login/components/LoginFormProfile/LoginFormProfile.scss, src/renderer/login/components/LoginFormProfile/index.js, src/renderer/register/actions/createAccountActions.js, src/renderer/register/actions/storeProfileActions.js, src/renderer/register/components/AccountDetails/AccountDatum/AccountDatum.js, src/renderer/register/components/AccountDetails/AccountDatum/AccountDatum.scss, src/renderer/register/components/AccountDetails/AccountDetails.js, src/renderer/register/components/AccountDetails/AccountDetails.scss, src/renderer/register/components/AccountDetails/SaveAccount/SaveAccount.js, src/renderer/register/components/AccountDetails/SaveAccount/SaveAccount.scss, src/renderer/register/components/AccountDetails/SaveAccount/index.js, src/renderer/register/components/Register/Register.js, src/renderer/register/components/Register/index.js, src/renderer/register/components/RegisterForm/RegisterForm.js, src/renderer/register/components/RegisterForm/index.js, src/renderer/register/shapes/accountShape.js, src/renderer/settings/components/NetworkSettings/index.js, src/renderer/shared/components/Icon/Icon.js, src/renderer/shared/values/profile.js
Adjust register/login flow
- Completely reworked register flow
- Added login through "wallet profiles" dropdown
- Added last used account support for the new wallet profiles
- Added hide/unhide functionality for account data
Onboarding was too difficult
Fixes https://github.com/nos/client/issues/893
=> feat(login/register): completely overhaul login/register flow

src/renderer/login/components/LoginFormProfile/LoginFormProfile.js, src/renderer/register/components/AccountDetails/AccountDatum/AccountDatum.js
Fixes an issue caused in the previous PR
It's broken
Fixes #
=> chore(login): fix issue when creating new wallet through login screen

src/renderer/login/actions/previousProfileActions.js, src/renderer/login/components/LoginFormPassphrase/LoginFormPassphrase.js, src/renderer/login/components/LoginFormProfile/index.js
splits auth state of profile dropdown and encrypted key w/ password
Fixes #
=> chore(auth): split previous auth values for profile and

src/renderer/account/components/TransactionsPanel/Send/index.js, yarn.lock
Fixed an issue where the wallet did not render when having the testnet selected
wallet loading broke
Fixes #
=> chore(account): fixed wallet not rendering using testNet

src/renderer/account/components/Portfolio/TransactionsPanel/Send/Send.js
=> chore(send): disable ability to send empty transactions

src/common/stylesheets/mixins.scss, src/renderer/root/components/AuthenticatedLayout/AuthenticatedLayout.scss
AuthenticatedLayout's content element had a 4px bump next to it (mostly visible on scrollable content). This hardwires the content's width to the max it's allowed (viewport - sidebar) and casts overflow to auto. This is needed for internal pages (app store) that rely on native content scrolling. Scrolling in webpages inherits from the webpage itself (i.e. if the content *should* scroll, it *will* scroll.)
_Note: for some reason using $sidebar-width in $content-width doesn't work 🙂_
Fix UI mistakes detected by @deanpress on dark/light mode switching
A/B'd with internal pages and external pages (nos.chat, nash, ...)
Fixes #
=> chore(browser): remove "bump" next to the browser

src/renderer/auth/actions/authActions.js
=> chore(auth): fix balances not loading

src/renderer/account/components/Management/Wallet/Wallet.js, src/renderer/account/components/Management/Wallet/Wallet.scss
It was possible to click the already active wallet.
This PR disables the popup from showing up and removes the hover of the already active wallet
Bad UX
Fixes #
=> chore(wallet): disable modal popup on already active wallet

src/renderer/browser/components/DAppContainer/DAppContainer.scss
Adds a default bg color to the webview page.
Viewing js/json/files in common in the nOS Browser has a weird gray color by default, rendering text not readable. 
This PR fixes this by setting a default color as white for these pages.
Text of files was unreadable
Fixes #
=> chore(appContainer): adds a default bg color to the webview page

src/renderer/browser/components/RequestsProcessor/Unauthenticated/Unauthenticated.js, static/preloads/api.js
=> chore(api): adjust the way errors are returned

.snyk, src/main/index.js, src/renderer/shared/components/NewWallet/Import/Import/Import.js, yarn.lock
=> chore(app): hide legacy import when empty and adjust default gpu setting

src/renderer/auth/components/Auth/Auth.js, src/renderer/shared/components/Alert/Alert.js, src/renderer/shared/components/Confirm/Confirm.js, src/renderer/shared/components/Modal/Modal.js, src/renderer/shared/components/Modal/OnClickOutside.js, src/renderer/shared/components/NewWallet/NewWallet/NewWallet.js
=> feat(modal): add ability to press escape or click outside to close modal

src/renderer/shared/components/Modal/OnClickOutside.js
The modal closed when clicking on a dropdown due to it being a portal and thus being "outside" of the modal
Fixes #
=> chore(modal): fix click outside not working when selecting dropdown

src/renderer/shared/components/NewWallet/Import/ExistingImport/ExistingImport.js, src/renderer/shared/components/NewWallet/Import/ExistingImport/index.js
Legacy import did not work when the legacy password did not match the current account password
Legacy import did not work when the legacy password did not match the current account password
Fixes #
=> chore(import): fix legacy import issue with mixed up passwords

electron-builder.json, src/common/util/getRPCEndpoint.js
=> chore(node): fix ssl issues
